Hello world Backend
looh16/hello-rails-back-end pull request #1
Opened 2022-12-07 09:31 UTC by looh16

Create an API endpoint that return a random greeting.

2022-12-08 20:25 UTC, Lucas-Masaba requested changes
# Hello @looh16  👋 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request ⚠️ 

- [ ] Please add a link to your React front-end project in your README to proceed

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏 💻 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @Lucas-Masaba in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-12-08 20:25 UTC, Lucas-Masaba commented on README.md
> +# 📖 [hello-rails-back-end] <a name="about-project"></a>
- [ ] In this README, please add a link to your React Front-End. This is a project requirement.

2022-12-08 21:51 UTC, descholar-ceo approved these changes
Hi @looh16 🤝 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
👍🏽 Implemented all remequirements ✔️ 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-09 06:11 UTC, looh16 commented
Thanks!

2022-12-09 06:11 UTC, merged